version: "2"
services:
    php:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ./Musical-World:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:latest
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: musical_world
            MYSQL_USER: world 
            MYSQL_PASSWORD: music
            MYSQL_ROOT_PASSWORD: music
            MYSQL_CHARSET: utf8mb4  # Specify the desired charset here
        volumes:
            - ./Musical-World/database:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - "8000:80"
        environment:
            MYSQL_USER: world
            MYSQL_PASSWORD: music
            MYSQL_ROOT_PASSWORD: music
volumes:
    persistent:
